// <auto-generated />
using System;
using FixEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FixEngine.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240104100724_ExecutionDecimalPositionId")]
    partial class ExecutionDecimalPositionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FixEngine.Enitity.Execution", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("AvgPx")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("ClOrdId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("CumQty")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExecId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ExecType")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("ExpireTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LeavesQty")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("OrdRejReason")
                        .IsRequired()
                        .HasColumnType("varchar(44)");

                    b.Property<string>("OrdStatus")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("OrdType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("OrderQty")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("PosId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TimeInForce")
                        .IsRequired()
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("TransactTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
